### ISSUE TITLE
Issue with compiling with gcc

### ISSUE THREAD

**Issue by EMACC99** [Gujavlu/hpc-2021-2-fftw#4]
ussing gcc didn't work for me to compile the program, I needed to use mpicc for compiling.

This was caused in an ubuntu system with mpich version 3.4.1 and fftw-3.3.9

**Comment by GustavoAlfredoZA** [comment]
Yep, mpicc works without problems with MPICH v3.4.* and FFTW v3.3.9, use it instead of gcc.
